spring:
  application:
    name: conv-mp-payment-calculation
  datasource:
    url: jdbc:postgresql://localhost:5432/conv_monitoring
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true        # SQL
    open-in-view: false # Отключаем OSIV (Open Session in View)

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false  # JSON

  sql:
    init:
      mode: never              # schema.sql + data.sql


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE    # Hibernate 6+
    ru.bank.conv.mp_payment_calculation: DEBUG

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method        # Сортирует эндпоинты по HTTP-методу (GET, POST)
    tags-sorter: alpha               # Сортирует контроллеры по алфавиту
    display-request-duration: true   # Показывает время выполнения запроса
    filter: true                     # Поиск по API
    default-models-expand-depth: 2   # Раскрывать модели DTO
  api-docs:
    path: /api-docs                  # стандартный endpoint JSON (OpenAPI spec)

gateway:
  integration-id: 2
  source: conv-mp-payment-calculation
  url: http://localhost:8080/v1/conv-uis-gateway
